using PBL3.DTO;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PBL3.BLL
{
    public class BLLKhachHang
    {
        QLCHTAN db = new QLCHTAN();
        private static BLLKhachHang _Instance;

        public static BLLKhachHang Instance
        {
            get
            {
                if (_Instance == null)
                {
                    _Instance = new BLLKhachHang();
                }
                return _Instance;
            }
            private set { }
        }

        private BLLKhachHang()
        {

        }

        public bool checkAddUpdate(string id)
        {
            bool Add = true;
            try
            {
                if (db.KhachHang.Find(id) != null)
                {
                    Add = false;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return Add;
        }

        public bool Delete(string id)
        {
            try
            {
                db.KhachHang.Find(id).IsDeleted = true;
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return false;
        }
        public string AutoGeneratedId()
        {
            string id_next = "";
            try
            {
                string id_max = db.KhachHang.Select(p => p.id_KhachHang).ToList().Max();
                if (id_max == null)
                {
                    id_next = "KH001";
                }
                else
                {
                    int max = Convert.ToInt32(id_max.Substring(id_max.Length - 3));
                    max++;
                    id_next = "KH" + ("000" + max).Substring(("000" + max).Length - 3);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return id_next;
        }
        public bool ExecuteAddUpdate(KhachHang t)
        {
            try
            {
                if (checkAddUpdate(t.id_KhachHang))
                {
                    db.KhachHang.Add(new KhachHang
                    {
                        id_KhachHang = t.id_KhachHang,
                        TenKhachHang = t.TenKhachHang,
                        NgaySinh = t.NgaySinh.Date,
                        GioiTinh = t.GioiTinh,
                        SoDienThoai = t.SoDienThoai,
                        DiaChi = t.DiaChi
                    });
                    db.SaveChanges();
                }
                else
                {
                    KhachHang kh = db.KhachHang.Find(t.id_KhachHang);
                    kh.TenKhachHang = t.TenKhachHang;
                    kh.DiaChi = t.DiaChi;
                    kh.GioiTinh = t.GioiTinh;
                    kh.SoDienThoai = t.SoDienThoai;
                    kh.NgaySinh = t.NgaySinh.Date;
                    db.SaveChanges();
                }
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return false;
        }

        public List<KhachHang_View> GetAll()
        {
            List<KhachHang_View> list = new List<KhachHang_View>();
            try
            {
                list = db.KhachHang
                        .Where(p => p.IsDeleted == false)
                        .Select(p => new KhachHang_View
                        {
                            id_KhachHang = p.id_KhachHang,
                            TenKhachHang = p.TenKhachHang,
                            NgaySinh = p.NgaySinh,
                            GioiTinh = p.GioiTinh ? "Nam" : "Nữ",
                            SoDienThoai = p.SoDienThoai,
                            DiaChi = p.DiaChi
                        })
                        .ToList();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return list;
        }

        public KhachHang GetById(string id)
        {
            KhachHang khachHang = new KhachHang();
            try
            {
                khachHang = db.KhachHang.Find(id);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return khachHang;
        }
        public List<KhachHang_View> Search(string name)
        {
            List<KhachHang_View> list = new List<KhachHang_View>();
            try
            {
                list = db.KhachHang
                        .Where(p => p.IsDeleted == false)
                        .Where(p => p.TenKhachHang.Contains(name.ToLower()))
                        .Select(p => new KhachHang_View
                        {
                            id_KhachHang = p.id_KhachHang,
                            TenKhachHang = p.TenKhachHang,
                            NgaySinh = p.NgaySinh,
                            GioiTinh = p.GioiTinh ? "Nam" : "Nữ",
                            SoDienThoai = p.SoDienThoai,
                            DiaChi = p.DiaChi
                        })
                        .ToList();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return list;
        }
        public int TongKhachHang()
        {
            int tong = 0;
            try
            {
                tong = db.KhachHang.Where(p => p.IsDeleted == false).Count();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return tong;
        }
    }
}
