using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using PBL3.DTO;
using PBL3.BLL;

namespace PBL3.View
{
    public partial class frmThucdon : Form
    {
        private string imageSourceFile = "";
        private string defaultImage = @".\image\default.jpg";
        public frmThucdon()
        {
            InitializeComponent();
        }

        private void frmThucdon_Load(object sender, EventArgs e)
        {
            EditorEnable(false);
            txtMaMonAn.Enabled = false;
            Reload();
            dgvThucdon.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvThucdon.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.AllCells;
        }

        public void EditorEnable(bool b)
        {
            txtTenMon.Enabled = b;
            txtGiaTien.Enabled = b;
            btnLuu.Enabled = b;
            btnHuy.Enabled = b;
            btnChonAnh.Enabled = b;
            btnThem.Enabled = !b;
            btnSua.Enabled = !b;
            btnXoa.Enabled = !b;
            dgvThucdon.Enabled = !b;
        }

        public void EditorReset()
        {
            txtMaMonAn.Text = "";
            txtTenMon.Text = "";
            txtGiaTien.Text = "";
            LoadImage(defaultImage);
        }

        public void LoadImage(string path)
        {
            Image img;
            using (var bmpTemp = new Bitmap(path))
            {
                img = new Bitmap(bmpTemp);
            }
            AnhMinhHoa.Image = img;
        }

        public void Reload()
        {
            dgvThucdon.DataSource = BLLMonAn.Instance.GetAll();
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            EditorReset();
            txtMaMonAn.Text = BLLMonAn.Instance.AutoGeneratedId();
            EditorEnable(true);
        }

        private void btnXoa_Click(object sender, EventArgs e)
        {
            if(dgvThucdon.SelectedRows.Count == 1)
            {
                string id_MonAn = dgvThucdon.SelectedRows[0].Cells["id_MonAn"].Value.ToString();
                DialogResult dr = MessageBox.Show("Bạn muốn xóa món ăn có id '"+id_MonAn+"'?","Xác nhận xóa",MessageBoxButtons.OKCancel,MessageBoxIcon.Question);
                if(dr == DialogResult.OK)
                {
                    BLLMonAn.Instance.Delete(id_MonAn);
                    Reload();
                }
            }
        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            if(dgvThucdon.SelectedRows.Count == 1)
            {
                EditorEnable(true);
            }           
        }

        private void dgvThucdon_DataBindingComplete(object sender, DataGridViewBindingCompleteEventArgs e)
        {
            dgvThucdon.Columns["id_MonAn"].HeaderText = "Mã món ăn";
            dgvThucdon.Columns["TenMonAn"].HeaderText = "Tên món ăn";
            dgvThucdon.Columns["GiaBan"].HeaderText = "Giá Bán";
        }

        private void dgvThucdon_SelectionChanged(object sender, EventArgs e)
        {
            if (dgvThucdon.SelectedRows.Count == 1)
            {
                string id_MonAn = dgvThucdon.SelectedRows[0].Cells["id_MonAn"].Value.ToString();
                MonAn monAn = BLLMonAn.Instance.GetById(id_MonAn);
                txtTenMon.Text = monAn.TenMonAn;
                txtGiaTien.Text = monAn.GiaBan.ToString();
                txtMaMonAn.Text = monAn.id_MonAn;
                imageSourceFile = monAn.imagePath;
                LoadImage(imageSourceFile);
            }
        }

        private void btnChonAnh_Click(object sender, EventArgs e)
        {
            openFileDialog1.Filter = "Select image(*.jpg; *.png; *.gif) | *.jpg; *.png; *.gif";
            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                imageSourceFile = openFileDialog1.FileName;
                LoadImage(imageSourceFile);
            }
        }

        private void btnLuu_Click(object sender, EventArgs e)
        {
            if (imageSourceFile == "")
            {
                imageSourceFile = defaultImage;
            }
            if(txtTenMon.Text == "")
            {
                MessageBox.Show("Vui lòng nhập tên món ăn!");
                return;
            }
            if(txtGiaTien.Text == "")
            {
                MessageBox.Show("Vui lòng nhập giá tiền");
                return;
            }
            BLLMonAn.Instance.ExecuteAddUpdate(new MonAn
            {
                id_MonAn = txtMaMonAn.Text,
                TenMonAn = txtTenMon.Text,
                GiaBan = Convert.ToInt32(txtGiaTien.Text),
                imagePath = imageSourceFile,
            });
            EditorEnable(false);
            Reload();
        }

        private void btnHuy_Click(object sender, EventArgs e)
        {
            dgvThucdon_SelectionChanged(sender, e);
            EditorEnable(false);
        }
    }
}
