//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAHD { get; set; }
        public string MAKH { get; set; }
        public string MANV { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public string MA_ORDER { get; set; }
    
        public virtual Khachhang Khachhang { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
